language: python
services:
  - "postgresql"
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script: psql -c "CREATE USER db_admin WITH PASSWORD '"${DB_PASSWORD}"' WITH CREATEDB;' -U postgres"

script:
  - "python manage.py test"