language: python
services:
  - postgresql
python:
  - 3.5
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
 - psql -c 'create database travis;' -U postgres
 - autopep8 --in-place --aggressive --recursive .
 - pep8 .
 - pyflakes .
 - autoflake --in-place --recursive --imports=django .

script:
  - python manage.py test home.tests