language: python

services:
  - postgresql

python:
  - 3.5

install:
  - pip install -r requirements.txt

before_script:
 - psql -c 'create database travis;' -U postgres
 - autopep8 --in-place --aggressive --recursive .
 - pep8 .
 - autoflake --in-place --recursive --imports=django .
 - pyflakes .

script:
  - python manage.py test home.tests
  - coverage run --source=home manage.py test home.tests

after_success:
 - coveralls
 - chmod a+x ./after_success_script.sh
 - ./after_success_script.sh